/**
 * Integration tests for the MCP server tool pipeline
 * Tests end-to-end flows: indexing → search → retrieval
 */

import { mkdir, rm, writeFile } from 'fs/promises';
import { join, resolve } from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { ApiReportIndexer } from '../src/services/api-indexer.js';
import { DocumentationIndexer } from '../src/services/indexer.js';
import { SearchEngine } from '../src/services/search.js';
import { SymbolSearchEngine } from '../src/services/symbol-search.js';
import { createGetDocHandler } from '../src/tools/get-doc/index.js';
import { createGetSymbolHandler } from '../src/tools/get-symbol/index.js';
import { createSearchDocsHandler } from '../src/tools/search-docs/index.js';
import { createSearchSymbolsHandler } from '../src/tools/search-symbols/index.js';
import { NgDiagramMCPServer } from '../src/server.js';
import type { MCPServerConfig } from '../src/types/index.js';

/**
 * Helper to wrap code in the API report markdown format
 */
function makeApiReport(tsCode: string): string {
  return `## API Report File for "test-lib"

> Do not edit this file.

\`\`\`ts

${tsCode}
\`\`\`
`;
}

describe('Server initialization', () => {
  const testDocsDir = join(process.cwd(), 'tests', 'fixtures', 'integration-docs');
  const TEST_BASE_URL = 'https://test.example.com';

  function testConfig(overrides: Partial<MCPServerConfig> = {}): MCPServerConfig {
    return {
      name: 'test-server',
      version: '1.0.0',
      docsPath: testDocsDir,
      baseUrl: TEST_BASE_URL,
      ...overrides,
    };
  }

  beforeEach(async () => {
    await mkdir(testDocsDir, { recursive: true });
  });

  afterEach(async () => {
    await rm(testDocsDir, { recursive: true, force: true });
  });

  it('should initialize with valid configuration', () => {
    expect(() => new NgDiagramMCPServer(testConfig())).not.toThrow();
  });

  it('should report not running before start', () => {
    const server = new NgDiagramMCPServer(testConfig());
    expect(server.isServerRunning()).toBe(false);
  });

  it('should handle non-existent docs directory gracefully', () => {
    expect(() => {
      new NgDiagramMCPServer(testConfig({ docsPath: '/invalid/path/that/does/not/exist' }));
    }).not.toThrow();
  });

  it('should handle invalid frontmatter without crashing', async () => {
    await writeFile(
      join(testDocsDir, 'invalid.md'),
      `---
title: Test
invalid: [broken yaml: {
---

Content`,
      'utf-8'
    );

    expect(() => new NgDiagramMCPServer(testConfig())).not.toThrow();
  });
});

describe('Documentation tool pipeline: search_docs → get_doc', () => {
  const testDocsDir = join(process.cwd(), 'tests', 'fixtures', 'integration-pipeline');
  const TEST_BASE_URL = 'https://test.example.com';

  let indexer: DocumentationIndexer;
  let searchHandler: ReturnType<typeof createSearchDocsHandler>;
  let getDocHandler: ReturnType<typeof createGetDocHandler>;

  beforeEach(async () => {
    await mkdir(join(testDocsDir, 'guides'), { recursive: true });

    // Create a realistic doc structure
    await writeFile(
      join(testDocsDir, 'intro.md'),
      `---
title: Quick Start
description: Get started with ng-diagram in minutes
---

Install the package:

\`\`\`bash
npm install ng-diagram
\`\`\`

## Basic Setup

Import the module and add it to your Angular application.

\`\`\`typescript
import { provideNgDiagram } from 'ng-diagram';
\`\`\`

## Creating Your First Diagram

Use the diagram component in your template.
`,
      'utf-8'
    );

    await writeFile(
      join(testDocsDir, 'guides', 'custom-nodes.md'),
      `---
title: Custom Nodes
description: How to create and style custom node components
---

## Node Templates

You can create custom node components using Angular templates.

Each node template receives the node data as input.

## Styling Nodes

Apply CSS classes to customize the appearance of your nodes.

### Colors

Use the \`nodeColor\` property to set the fill color.

### Borders

Use standard CSS border properties.
`,
      'utf-8'
    );

    await writeFile(
      join(testDocsDir, 'guides', 'edges.md'),
      `---
title: Edge Routing
description: Configure how edges are drawn between nodes
---

## Routing Algorithms

ng-diagram supports multiple routing algorithms:

- **Bezier**: Smooth curved edges (default)
- **Straight**: Direct line connections
- **Orthogonal**: Right-angle connections

## Custom Edge Labels

You can attach labels to edges using the edge label component.
`,
      'utf-8'
    );

    indexer = new DocumentationIndexer({
      docsPath: testDocsDir,
      extensions: ['.md', '.mdx'],
      baseUrl: TEST_BASE_URL,
    });
    const sections = await indexer.buildIndex();
    const searchEngine = new SearchEngine(sections);

    searchHandler = createSearchDocsHandler(searchEngine);
    getDocHandler = createGetDocHandler(indexer);
  });

  afterEach(async () => {
    await rm(testDocsDir, { recursive: true, force: true });
  });

  it('should find docs by keyword and retrieve full page content', async () => {
    // Step 1: Search for "custom nodes"
    const searchResult = await searchHandler({ query: 'custom nodes' });

    expect(searchResult.results.length).toBeGreaterThanOrEqual(1);
    const match = searchResult.results.find((r) => r.pageTitle === 'Custom Nodes');
    expect(match).toBeDefined();
    expect(match!.path).toBe('guides/custom-nodes.md');
    expect(match!.url).toContain('test.example.com');

    // Step 2: Use the path from search to get the full doc
    const doc = await getDocHandler({ path: match!.path });

    expect(doc.title).toBe('Custom Nodes');
    expect(doc.body).toContain('## Node Templates');
    expect(doc.body).toContain('## Styling Nodes');
    expect(doc.body).not.toContain('title: Custom Nodes'); // no frontmatter
  });

  it('should return section-level results with correct anchors', async () => {
    const searchResult = await searchHandler({ query: 'routing algorithms' });

    expect(searchResult.results.length).toBeGreaterThanOrEqual(1);
    const match = searchResult.results[0];
    expect(match.pageTitle).toBe('Edge Routing');
    expect(match.sectionTitle).toBe('Routing Algorithms');
    expect(match.url).toBe(`${TEST_BASE_URL}/docs/guides/edges#routing-algorithms`);
    expect(match.content).toContain('Bezier');
    expect(match.content).toContain('Straight');
    expect(match.content).toContain('Orthogonal');
  });

  it('should find content across multiple pages and limit results', async () => {
    // "component" appears in both intro.md and custom-nodes.md
    const searchResult = await searchHandler({ query: 'component', limit: 2 });

    expect(searchResult.results).toHaveLength(2);
  });

  it('should return empty results for unrelated queries', async () => {
    const searchResult = await searchHandler({ query: 'quantum physics' });

    expect(searchResult.results).toEqual([]);
  });

  it('should return description only on first section of a page', async () => {
    const searchResult = await searchHandler({ query: 'edge routing' });

    const edgeResults = searchResult.results.filter((r) => r.pageTitle === 'Edge Routing');
    expect(edgeResults.length).toBeGreaterThanOrEqual(1);

    // At most one section should have description
    const withDescription = edgeResults.filter((r) => r.description !== undefined);
    expect(withDescription.length).toBeLessThanOrEqual(1);
    if (withDescription.length === 1) {
      expect(withDescription[0].description).toBe('Configure how edges are drawn between nodes');
    }
  });

  it('should get_doc fail gracefully for non-existent paths', async () => {
    await expect(getDocHandler({ path: 'nonexistent.md' })).rejects.toThrow('Document not found');
  });

  it('should reject path traversal in get_doc', async () => {
    await expect(getDocHandler({ path: '../../etc/passwd' })).rejects.toThrow(
      'Path must be a relative path within the docs directory'
    );
  });
});

describe('API symbol tool pipeline: search_symbols → get_symbol', () => {
  const fixtureDir = join(process.cwd(), 'tests', 'fixtures', 'integration-api');

  let apiIndexer: ApiReportIndexer;
  let searchSymbolsHandler: ReturnType<typeof createSearchSymbolsHandler>;
  let getSymbolHandler: ReturnType<typeof createGetSymbolHandler>;

  beforeEach(async () => {
    await mkdir(fixtureDir, { recursive: true });

    const report = makeApiReport(`
import { Provider } from '@angular/core';
import * as i0 from '@angular/core';

// @public
export interface Point {
    x: number;
    y: number;
}

// @public
export interface Size {
    width: number;
    height: number;
}

// @public
export class DiagramComponent {
    constructor();
    addNode(node: Node): void;
    removeNode(id: string): void;
    readonly nodes: Signal<Node[]>;
    // (undocumented)
    static ɵcmp: i0.ɵɵComponentDeclaration<DiagramComponent, "ng-diagram", never>;
    // (undocumented)
    static ɵfac: i0.ɵɵFactoryDeclaration<DiagramComponent, never>;
}

// @public
export function provideNgDiagram(config?: DiagramConfig): Provider[];

// @public
export type PortSide = 'top' | 'right' | 'bottom' | 'left';

// @public @deprecated (undocumented)
export const LegacyComponent: typeof DiagramComponent;

// @internal
export type InternalType = string;

// @public
type Node_2<T = unknown> = SimpleNode<T> | GroupNode<T>;
export { Node_2 as Node }

// @public
export enum Alignment {
    Center = "center",
    Start = "start",
    End = "end",
}
`);

    await writeFile(join(fixtureDir, 'test.api.md'), report, 'utf-8');

    apiIndexer = new ApiReportIndexer(join(fixtureDir, 'test.api.md'));
    const symbols = await apiIndexer.buildIndex();
    const symbolSearch = new SymbolSearchEngine(symbols);

    searchSymbolsHandler = createSearchSymbolsHandler(symbolSearch);
    getSymbolHandler = createGetSymbolHandler(apiIndexer);
  });

  afterEach(async () => {
    await rm(fixtureDir, { recursive: true, force: true });
  });

  it('should find a symbol by name and retrieve its full details', async () => {
    // Step 1: Search for "DiagramComponent"
    const searchResult = await searchSymbolsHandler({ query: 'DiagramComponent' });

    expect(searchResult.results.length).toBeGreaterThanOrEqual(1);
    const match = searchResult.results.find((r) => r.name === 'DiagramComponent');
    expect(match).toBeDefined();
    expect(match!.kind).toBe('class');

    // Step 2: Use the name from search to get full details
    const symbol = await getSymbolHandler({ name: match!.name });

    expect(symbol.name).toBe('DiagramComponent');
    expect(symbol.kind).toBe('class');
    expect(symbol.signature).toContain('addNode(node: Node): void');
    expect(symbol.signature).toContain('removeNode(id: string): void');
    expect(symbol.signature).not.toContain('ɵcmp'); // Angular artifacts stripped
    expect(symbol.signature).not.toContain('ɵfac');
    expect(symbol.importStatement).toBe("import { DiagramComponent } from 'ng-diagram';");
  });

  it('should filter symbols by kind', async () => {
    const interfaces = await searchSymbolsHandler({ query: 'Point Size', kind: 'interface' });

    expect(interfaces.results.length).toBeGreaterThanOrEqual(1);
    interfaces.results.forEach((r) => {
      expect(r.kind).toBe('interface');
    });

    const functions = await searchSymbolsHandler({ query: 'provide', kind: 'function' });

    expect(functions.results).toHaveLength(1);
    expect(functions.results[0].name).toBe('provideNgDiagram');
  });

  it('should handle re-exported symbols (Node_2 → Node)', async () => {
    const searchResult = await searchSymbolsHandler({ query: 'Node' });

    const nodeResult = searchResult.results.find((r) => r.name === 'Node');
    expect(nodeResult).toBeDefined();
    expect(nodeResult!.kind).toBe('type');

    // Should not find the internal name
    const internalResult = searchResult.results.find((r) => r.name === 'Node_2');
    expect(internalResult).toBeUndefined();

    // Full details should use the public name
    const symbol = await getSymbolHandler({ name: 'Node' });
    expect(symbol.signature).toContain('SimpleNode<T> | GroupNode<T>');
    expect(symbol.importStatement).toBe("import { Node } from 'ng-diagram';");
  });

  it('should mark deprecated symbols', async () => {
    const symbol = await getSymbolHandler({ name: 'LegacyComponent' });

    expect(symbol.jsDoc).toBe('@deprecated');
  });

  it('should not expose @internal symbols', async () => {
    const searchResult = await searchSymbolsHandler({ query: 'InternalType' });

    expect(searchResult.results.find((r) => r.name === 'InternalType')).toBeUndefined();

    await expect(getSymbolHandler({ name: 'InternalType' })).rejects.toThrow('Symbol not found');
  });

  it('should find enum symbols', async () => {
    const searchResult = await searchSymbolsHandler({ query: 'Alignment', kind: 'enum' });

    expect(searchResult.results.length).toBeGreaterThanOrEqual(1);
    expect(searchResult.results[0].name).toBe('Alignment');

    const symbol = await getSymbolHandler({ name: 'Alignment' });
    expect(symbol.kind).toBe('enum');
    expect(symbol.signature).toContain('Center = "center"');
  });

  it('should get_symbol fail for unknown names', async () => {
    await expect(getSymbolHandler({ name: 'DoesNotExist' })).rejects.toThrow('Symbol not found');
  });
});

describe('Combined pipeline: docs + API symbols', () => {
  const testDocsDir = join(process.cwd(), 'tests', 'fixtures', 'integration-combined-docs');
  const fixtureDir = join(process.cwd(), 'tests', 'fixtures', 'integration-combined-api');
  const TEST_BASE_URL = 'https://test.example.com';

  let searchHandler: ReturnType<typeof createSearchDocsHandler>;
  let getDocHandler: ReturnType<typeof createGetDocHandler>;
  let searchSymbolsHandler: ReturnType<typeof createSearchSymbolsHandler>;
  let getSymbolHandler: ReturnType<typeof createGetSymbolHandler>;

  beforeEach(async () => {
    await mkdir(testDocsDir, { recursive: true });
    await mkdir(fixtureDir, { recursive: true });

    // Create a doc that references API symbols
    await writeFile(
      join(testDocsDir, 'palette.md'),
      `---
title: Palette Component
description: Drag and drop nodes from a palette onto the diagram
---

## Overview

The palette component lets users drag predefined node templates onto the canvas.

## Usage

Use the \`provideNgDiagram\` function to set up the palette:

\`\`\`typescript
import { provideNgDiagram } from 'ng-diagram';
\`\`\`

## Configuration

Pass a \`PaletteConfig\` interface to customize behavior.
`,
      'utf-8'
    );

    const report = makeApiReport(`
// @public
export function provideNgDiagram(config?: DiagramConfig): Provider[];

// @public
export interface PaletteConfig {
    enabled: boolean;
    position: 'left' | 'right';
}
`);
    await writeFile(join(fixtureDir, 'test.api.md'), report, 'utf-8');

    // Build both indexes
    const docIndexer = new DocumentationIndexer({
      docsPath: testDocsDir,
      extensions: ['.md'],
      baseUrl: TEST_BASE_URL,
    });
    const sections = await docIndexer.buildIndex();
    const searchEngine = new SearchEngine(sections);

    const apiIndexer = new ApiReportIndexer(join(fixtureDir, 'test.api.md'));
    const symbols = await apiIndexer.buildIndex();
    const symbolSearch = new SymbolSearchEngine(symbols);

    searchHandler = createSearchDocsHandler(searchEngine);
    getDocHandler = createGetDocHandler(docIndexer);
    searchSymbolsHandler = createSearchSymbolsHandler(symbolSearch);
    getSymbolHandler = createGetSymbolHandler(apiIndexer);
  });

  afterEach(async () => {
    await rm(testDocsDir, { recursive: true, force: true });
    await rm(fixtureDir, { recursive: true, force: true });
  });

  it('should find docs mentioning an API symbol, then look up that symbol', async () => {
    // User asks: "how do I use provideNgDiagram?"

    // Step 1: Search docs for usage context
    const docResults = await searchHandler({ query: 'provideNgDiagram' });
    expect(docResults.results.length).toBeGreaterThanOrEqual(1);
    expect(docResults.results[0].pageTitle).toBe('Palette Component');

    // Step 2: Get full doc for detailed usage instructions
    const doc = await getDocHandler({ path: docResults.results[0].path });
    expect(doc.body).toContain('provideNgDiagram');

    // Step 3: Look up the API signature
    const symbolResults = await searchSymbolsHandler({ query: 'provideNgDiagram' });
    expect(symbolResults.results[0].name).toBe('provideNgDiagram');

    // Step 4: Get full symbol details
    const symbol = await getSymbolHandler({ name: 'provideNgDiagram' });
    expect(symbol.kind).toBe('function');
    expect(symbol.signature).toContain('DiagramConfig');
    expect(symbol.importStatement).toBe("import { provideNgDiagram } from 'ng-diagram';");
  });

  it('should find related config interface from docs context', async () => {
    // User reads about "PaletteConfig" in the docs
    const docResults = await searchHandler({ query: 'PaletteConfig' });
    expect(docResults.results.length).toBeGreaterThanOrEqual(1);

    // Then looks up the actual interface
    const symbol = await getSymbolHandler({ name: 'PaletteConfig' });
    expect(symbol.kind).toBe('interface');
    expect(symbol.signature).toContain('enabled: boolean');
    expect(symbol.signature).toContain("position: 'left' | 'right'");
  });
});

describe('Pipeline with real monorepo data', () => {
  const docsPath = resolve(process.cwd(), '../../apps/docs/src/content/docs');
  const apiReportPath = resolve(process.cwd(), '../../packages/ng-diagram/api-report/ng-diagram.api.md');
  const BASE_URL = 'https://www.ngdiagram.dev';

  let searchHandler: ReturnType<typeof createSearchDocsHandler>;
  let getDocHandler: ReturnType<typeof createGetDocHandler>;
  let searchSymbolsHandler: ReturnType<typeof createSearchSymbolsHandler>;
  let getSymbolHandler: ReturnType<typeof createGetSymbolHandler>;

  beforeEach(async () => {
    const docIndexer = new DocumentationIndexer({
      docsPath,
      extensions: ['.md', '.mdx'],
      baseUrl: BASE_URL,
    });
    const sections = await docIndexer.buildIndex();
    const searchEngine = new SearchEngine(sections);

    const apiIndexer = new ApiReportIndexer(apiReportPath);
    const symbols = await apiIndexer.buildIndex();
    const symbolSearch = new SymbolSearchEngine(symbols);

    searchHandler = createSearchDocsHandler(searchEngine);
    getDocHandler = createGetDocHandler(docIndexer);
    searchSymbolsHandler = createSearchSymbolsHandler(symbolSearch);
    getSymbolHandler = createGetSymbolHandler(apiIndexer);
  });

  it('should search real docs, get a page, and verify content', async () => {
    const searchResult = await searchHandler({ query: 'quick start', limit: 3 });

    expect(searchResult.results.length).toBeGreaterThanOrEqual(1);

    // Get the first result's full page
    const firstResult = searchResult.results[0];
    const doc = await getDocHandler({ path: firstResult.path });

    expect(doc.title).toBeTruthy();
    expect(doc.body.length).toBeGreaterThan(0);
    expect(doc.url).toContain('ngdiagram.dev');
  });

  it('should search real API symbols and get full details', async () => {
    const searchResult = await searchSymbolsHandler({ query: 'NgDiagramComponent' });

    expect(searchResult.results.length).toBeGreaterThanOrEqual(1);
    const match = searchResult.results.find((r) => r.name === 'NgDiagramComponent');
    expect(match).toBeDefined();

    const symbol = await getSymbolHandler({ name: 'NgDiagramComponent' });
    expect(symbol.kind).toBe('class');
    expect(symbol.signature).not.toContain('ɵcmp');
    expect(symbol.importStatement).toBe("import { NgDiagramComponent } from 'ng-diagram';");
  });

  it('should find provideNgDiagram in both docs and API', async () => {
    const docResults = await searchHandler({ query: 'provideNgDiagram' });
    const symbolResults = await searchSymbolsHandler({ query: 'provideNgDiagram' });

    // Should exist in both indexes
    expect(docResults.results.length).toBeGreaterThanOrEqual(1);
    expect(symbolResults.results.length).toBeGreaterThanOrEqual(1);
    expect(symbolResults.results[0].name).toBe('provideNgDiagram');
  });
});
